name: RPGTaleCraftPlugin
main: fr.mrdraong.rpgtalecraft.RPGTaleCraftPlugin
version: 1.0
api-version: 1.21.1
commands:
  tribebook:
    description: "Give the tribes book to the player"
    usage: /tribebook
  tribepage:
    description: "Execute the action associate with the tribe book page"
    usage: /tribepage <pageIdentifier> <playerUUID>
  tribequit:
    description: "Remove your tribe and tribe item's"
    usage: /tribequit